# CS431 - CÁC KỸ THUẬT HỌC SÂU VÀ ỨNG DỤNG

**Hướng dẫn**:
- Hoàn tất tất cả các mục có comment `YOUR CODE HERE`

---

# LUYỆN TẬP NUMPY - PHẦN 1

In [ ]:
import numpy as np

## Bài 1: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 0.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([0., 0., 0., 0., 0.])
```

In [ ]:
def init_zeros(n):
    return np.zeros(n)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
# cell chấm điểm 1
assert init_zeros(5).shape == (5, )
assert np.sum(abs(init_zeros(5) - np.array([0, 0, 0, 0, 0]))) == 0

In [ ]:
# cell chấm điểm 2

## Bài 2: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số 1.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([1, 1, 1, 1, 1])
```

In [ ]:
def init_ones(n):
    return np.ones(n)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_ones(5)

array([1., 1., 1., 1., 1.])

In [ ]:
# cell chấm điểm 3
assert init_ones(5).shape == (5, )
assert np.sum(abs(init_ones(5) - np.array([1, 1, 1, 1, 1]))) == 0

In [ ]:
# cell chấm điểm 4

## Bài 3: Khởi tạo vector
Khởi tạo một vector gồm `n` phần tử gồm toàn số `x`.

Ví dụ:

Input:
```
n = 5
x = 3.5
```

Output:
```
array([3.5, 3.5, 3.5, 3.5, 3.5])
```

In [ ]:
def init_all_x(n, x):
    return np.full(n, x)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_all_x(5, 3.5)

array([3.5, 3.5, 3.5, 3.5, 3.5])

In [ ]:
# cell chấm điểm 5
assert init_all_x(5, 3.5).shape == (5, )
assert np.sum(abs(init_all_x(5, 3.5) - np.array([3.5, 3.5, 3.5, 3.5, 3.5]))) == 0

In [ ]:
# cell chấm điểm 6

## Bài 4: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `0..n-1`.

Ví dụ:

Input:
```
n = 5
```

Output:
```
array([0, 1, 2, 3, 4])
```

In [ ]:
def init_range(n):
    return np.arange(n)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_range(5)

array([0, 1, 2, 3, 4])

In [ ]:
# cell chấm điểm 7
assert init_range(5).shape == (5, )
assert np.sum(abs(init_range(5) - np.array([0,1,2,3,4]))) == 0

In [ ]:
# cell chấm điểm 8

## Bài 5: Khởi tạo vector
Khởi tạo một vector có số phần tử là `n` gồm các số nguyên tăng dần từ `x, x+1,...,x+n-1` (chuỗi số bắt đầu từ `x`)

Ví dụ:

Input:
```
n = 5
x = 3.5
```

Output:
```
array([3.5, 4.5, 5.5, 6.5, 7.5])
```

In [ ]:
def init_range(n, x):
    return np.arange(x, x + n)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_range(5, 3.5)

array([3.5, 4.5, 5.5, 6.5, 7.5])

In [ ]:
# cell chấm điểm 9
assert init_range(5, 3).shape == (5, )
assert np.sum(abs(init_range(5, 3) - np.array([3, 4, 5, 6, 7]))) == 0

In [ ]:
# cell chấm điểm 10

## Bài 6: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm toàn số `K`.

Ví dụ:

Input:
```
m = 3
n = 4
K = 5
```

Output:
```
array([[5., 5., 5., 5.],
       [5., 5., 5., 5.],
       [5., 5., 5., 5.]])
```

In [ ]:
def init_mat_K(m, n, K):
    return np.full((m, n), K)
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_mat_K(3, 4, 5)

array([[5, 5, 5, 5],
       [5, 5, 5, 5],
       [5, 5, 5, 5]])

In [ ]:
# cell chấm điểm 11
assert init_mat_K(2,3,4).shape == (2, 3)
assert np.sum(abs(init_mat_K(2,3,4) - np.array([[4, 4, 4], [4, 4, 4]]))) == 0

In [ ]:
# cell chấm điểm 12

## Bài 7: Khởi tạo ma trận
Khởi tạo ma trận kích thước `m x n` gồm tăng dần từ trái sang phải, từ trên xuống dưới. Phần tử nhỏ nhất bắt đầu từ 1.

Ví dụ:

Input:
```
m = 2
n = 4
```

Output:
```
array([[1, 2, 3, 4],
       [5, 6, 7, 8]])
```

In [ ]:
def init_mat_increase(m, n):
    return np.arange(1, m * n + 1).reshape((m, n))
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
init_mat_increase(2, 4)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [ ]:
# cell chấm điểm 13
assert init_mat_increase(2,3).shape == (2, 3)
assert np.sum(abs(init_mat_increase(2,3) - np.array([[1, 2, 3], [4, 5, 6]]))) == 0

In [ ]:
# cell chấm điểm 14

## Bài 8: Tích vô hướng 2 vector
Viết hàm `solution` nhận vào 2 List `a` và `b` có kiểu dữ liệu là `float`, tính tích vô hướng giữa hai vector `a` và `b`.

Ví dụ:

Input:
```
a = [1, 2]
b = [3, 4]
```

Output:
```
11
```

In [1]:
import numpy as np

def product_on_list(a, b):
    # B1: chuyển a và b thành dạng numpy array
    a_np = np.array(a,dtype=float)
    b_np = np.array(b,dtype= float)
    raise NotImplementedError()

    # B2: tính tích vô hướng bằng hàm dot
    tichvohuong = np.dot(a_np, b_np)
    return tichvohuong
    #raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
product_on_list([1, 2], [3, 4])

NotImplementedError: ignored

In [ ]:
# cell chấm điểm 15
assert product_on_list([1, 2], [2, 3]) == 8
assert product_on_list([1, 2], [0, 0]) == 0

In [ ]:
# cell chấm điểm 16

## Bài 9: Tích vô hướng 2 ma trận
Viết hàm nhận vào hai *ma trận* `X` và *ma trận* `W`, trả về giá trị tích `M` (dot product) theo công thức sau:
```
M = (x^T)W
```
Trong đó, `x^T` là phép chuyển vị của `x`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Ví dụ:


Input:
```
X = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)

W = np.array([
    [1, 1, 1],
    [0, 0, 0]]
)
```

Output:
```
[[1, 1, 1],
 [1, 1, 1],
 [1, 1, 1]]
```

In [ ]:
def product_vec_mat(X, W):
    result = np.dot(X.T, W)
    return result
    raise NotImplementedError()

In [ ]:
# thử nghiệm với ví dụ của đề bài
X = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
W = np.array([
  [1, 1, 1],
  [0, 0, 0]
])
product_vec_mat(X, W)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
# cell chấm điểm 17
X = np.array([
    [1, 2, 3],
    [4, 5, 6]
])
W = np.array([
    [7, 8, 9],
    [10, 11, 12]
])

assert np.sum(abs(product_vec_mat(X, W)-np.array([
    [47, 52, 57],
    [64, 71, 78],
    [81, 90, 99]
]))) < 0.0001

In [ ]:
# cell chấm điểm 18

## Bài 10: Tổng các ma trận và vector
Viết hàm nhận vào hai ma trận `X` và `W`, trả về giá trị `M` theo công thức sau:
```
M = 2 (X^T + W).X
```
Trong đó `X^T` là phép chuyển vị của `X`. Cần kiểm tra số chiều để bảo đảm phép tính luôn tính được trước khi thực hiện phép tính, trả về giá trị `None` nếu số chiều không tương thích.

Ví dụ:


Input:
```
X = np.array([
    [1, 1],
    [0, 0]
])

W = np.array([
    [1, 1],
    [0, 0]
])
```

Output:
```
array([[4, 4],
       [2, 2]])
```

In [ ]:
def prod_sum_mat(x, w):
    result = 2 * (np.dot(X.T + W, X))
    return result
    raise NotImplementedError()

In [ ]:
# cell chấm điểm 19
X = np.array([
  [1, 1],
  [2, 3],
  [5, 4]
])

W = np.array([
  [1, 2, 3],
  [4, 5, 6]
])

assert np.sum(abs(prod_sum_mat(X, W)-np.array([
    [100, 92],
    [142, 138]
]))) < 0.0001

In [ ]:
# cell chấm điểm 20